/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "awsreacttodo-20220623123026-hostingbucket-todo",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://awsreacttodo-20220623123026-hostingbucket-todo.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:15d109a5-0bf3-4051-ab8a-b5f389cffabd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Okq0Kbeim",
    "aws_user_pools_web_client_id": "2ipb0q6jtq4jbti3tcv2mlsllt",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cyidjgv27nb23lhoiis32j3jly.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "null"
};


export default awsmobile;
